**Numpy**

In [ ]:
import numpy as np

**python List**

In [6]:
# basic python list
lst1=[1,2,2,3,4,6]
lst1

[1, 2, 2, 3, 4, 6]

In [10]:
lst2=['name',3,5,[2,3,4,5],True]
lst2

['name', 3, 5, [2, 3, 4, 5], True]

**Numpy - Numeric Python**

In [13]:
# Numpy array dtype -- ndarray
np1=np.array([2,3,4,1,3,5,6])
np1

array([2, 3, 4, 1, 3, 5, 6])

In [15]:
# shape of array
np1.shape

(7,)

In [17]:
# by range
np2=np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# range by step
np3=np.arange(0,10,2)
np3

array([0, 2, 4, 6, 8])

In [42]:
# multi dimensional array
npp=np.array([[1,2,4],[5,3,0],[4,6,8]])
npp

array([[1, 2, 4],
       [5, 3, 0],
       [4, 6, 8]])

In [44]:
npp.shape

(3, 3)

In [23]:
# Zeros
np4=np.zeros(10)
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
#2-d array
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
# full 
np5=np.full((10),6)
np5

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [31]:
np6=np.full((2,5),6)
np6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [37]:
# convert python list to numpy array
np7=np.array(lst1)
np7

array([1, 2, 2, 3, 4, 6])

In [39]:
lst2=['name',3,5,[2,3,4,5],True]
np8=np.array(lst2)
np8

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**Slicing Numpy array**

In [46]:
np11=np.array([1,2,3,5,6,7,8,9,4])
np11[1:5]

array([2, 3, 5, 6])

In [48]:
np11[3:]

array([5, 6, 7, 8, 9, 4])

In [50]:
np11[-3:-1]

array([8, 9])

In [52]:
# steps
np11[1:5:2]

array([2, 5])

In [54]:
np11[::2]

array([1, 3, 6, 8, 4])

In [56]:
# reverse
np11[::-1]

array([4, 9, 8, 7, 6, 5, 3, 2, 1])

**2-d array sclicing**

In [59]:
np12=np.array([[1,2,3,4],[3,2,5,4]])
np12

array([[1, 2, 3, 4],
       [3, 2, 5, 4]])

In [61]:
np12[1,2]

5

In [71]:
np12[0:2,1:3] 

array([[2, 3],
       [2, 5]])

**Universal Function**

In [74]:
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
# sqaure root of each element
np.sqrt(np2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [78]:
# absolute value
np111=np.array([3,4,5,-2,3,-4,-5,30,-34])
np.absolute(np111)

array([ 3,  4,  5,  2,  3,  4,  5, 30, 34])

In [80]:
# Exponents
np.exp(np2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [82]:
np.max(np111)

30

In [84]:
np.min(np111)

-34

In [86]:
 # sign 
np.sign(np111)

array([ 1,  1,  1, -1,  1, -1, -1,  1, -1])

In [88]:
# Trignometric 
np.log(np2)

C:\Users\arshi\AppData\Local\Temp\ipykernel_12580\1065845855.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(np2)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [90]:
np.sin(np2)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

**Copy Vs View**

In [93]:
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
# Create a view
np2_1=np2.view()
np2_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np2[3]=22
np2

array([ 0,  1,  2, 22,  4,  5,  6,  7,  8,  9])

In [99]:
np2_1

array([ 0,  1,  2, 22,  4,  5,  6,  7,  8,  9])

In [101]:
np2_1[2]=21
np2_1

array([ 0,  1, 21, 22,  4,  5,  6,  7,  8,  9])

In [103]:
np2

array([ 0,  1, 21, 22,  4,  5,  6,  7,  8,  9])

In [107]:
# copy
np2_2=np2.copy()
np2_2

array([ 0,  1, 21, 22,  4,  5,  6,  7,  8,  9])

In [109]:
np2[2]=2
np2

array([ 0,  1,  2, 22,  4,  5,  6,  7,  8,  9])

In [111]:
np2_2

array([ 0,  1, 21, 22,  4,  5,  6,  7,  8,  9])

In [113]:
np2_2[3]=3
np2_2

array([ 0,  1, 21,  3,  4,  5,  6,  7,  8,  9])

In [115]:
np2

array([ 0,  1,  2, 22,  4,  5,  6,  7,  8,  9])

**Shape and Reshape**

In [118]:
np2.shape

(10,)

In [120]:
np2d=np.array([[1,2],[3,4],[5,6]])
np2d.shape

(3, 2)

In [140]:
# reshape
np33=np.arange(1,13)
np33

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [142]:
# reshape to 2d
np33.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
np2d.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [144]:
# reshape to 3d
np33.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [148]:
# flatten to 1d
np33.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**iterate through numpy array**

In [151]:
# through 1d
np1=np.arange(1,11)
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [153]:
for x in np1:
    print(x)

1
2
3
4
5
6
7
8
9
10


In [155]:
# through 2d
np2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
np2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [157]:
for x in np2:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [159]:
for x in np2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [175]:
# using np.nditer()
for x in np.nditer(np2):
    print(x)

1
2
3
4
5
6
7
8
9
10


In [165]:
# through 3d
np3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
np3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [167]:
for x in np3:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [169]:
for x in np3:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [171]:
for x in np3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [173]:
# using np.nditer()
for x in np.nditer(np3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


**sorting numpy array**

In [178]:
np1=np.array([1,4,3,2,5,7,3])
np1

array([1, 4, 3, 2, 5, 7, 3])

In [182]:
np.sort(np1)

array([1, 2, 3, 3, 4, 5, 7])

In [186]:
np2=np.array(['ars','gshs','zhaf','dgh','asd'])
print(np2)
print(np.sort(np2))

['ars' 'gshs' 'zhaf' 'dgh' 'asd']
['ars' 'asd' 'dgh' 'gshs' 'zhaf']


In [190]:
np3=np.array([True,False,False,True,False])
np.sort(np3)

array([False, False, False,  True,  True])

In [192]:
# 2d array

np4=np.array([[5,34,3],[4,5,23]])
np4

array([[ 5, 34,  3],
       [ 4,  5, 23]])

In [194]:
np.sort(np4)

array([[ 3,  5, 34],
       [ 4,  5, 23]])

**Search**

In [197]:
np1

array([1, 2, 3, 3, 4, 5, 7])

In [199]:
x=np.where(np1==3)
x

(array([2, 3], dtype=int64),)

In [212]:
np1[x]

array([3, 3])

In [214]:
# return even 
x=np.where(np1%2==0)
x

(array([1, 4], dtype=int64),)

In [216]:
np1[x]

array([2, 4])

**Filter numpy array**

In [219]:
np1

array([1, 2, 3, 3, 4, 5, 7])

In [221]:
x=[True,False,True,True,False,False,False]
np1[x]

array([1, 3, 3])

In [223]:
def filt(arr):
    filtered=[]
    for x in np1:
        if x%2==0:
            filtered.append(True)
        else:
            filtered.append(False)
    return arr[filtered]

print(filt(np1))

[2 4]


In [225]:
# shortcut
filtered=np1 % 2==0
np1[filtered]

array([2, 4])